version: '3.8'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    expose:
      - "6379"
    networks:
      - redis_network

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - fastapi_network
      - redis_network

networks:
  fastapi_network:
  redis_network:
    driver: bridge