version: '3.8'

services:
  redis:
    image: redis
    ports:
      - "16379:6379"
    expose:
      - "6379"
    networks:
      fastapi-network:
        aliases:
          - redis

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      fastapi-network:
        aliases:
          - redis