version: '3.8'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    expose:
      - "6379"
    networks:
      - my_network

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - my_network
networks:
  my_network: